from dataclasses import dataclass
import os
from pathlib import Path
import re
import socket
import tempfile
import time
import uuid


SIP_REQUIRED_KEYS = ("mango_sip_server", "mango_sip_login", "mango_sip_password")
HOST_PATTERN = re.compile(r"^[a-z0-9.-]+$")
LOGIN_PATTERN = re.compile(r"^[A-Za-z0-9_.+/@-]+$")
PHONE_PATTERN = re.compile(r"^\+[1-9][0-9]{10,14}$")


class SipError(RuntimeError):
    pass


@dataclass(frozen=True)
class SipStatus:
    state: str
    label: str
    detail: str
    registered: bool = False


def normalize_server(value: str) -> str:
    server = value.strip().lower()
    if server.startswith("sip:"):
        server = server[4:]
    server = server.lstrip("@").rstrip(".")
    if not server or not HOST_PATTERN.fullmatch(server):
        raise SipError("Некорректный SIP-сервер Mango")
    return server


def validate_login(value: str) -> str:
    login = value.strip()
    if not login or not LOGIN_PATTERN.fullmatch(login):
        raise SipError("Некорректный SIP-логин Mango")
    return login


def validate_extension(value: str) -> str:
    extension = value.strip()
    if not extension.isdigit() or len(extension) > 20:
        raise SipError("Некорректный внутренний номер Mango")
    return extension


def validate_password(value: str) -> str:
    if not value or len(value) > 256 or any(character in value for character in "\r\n;"):
        raise SipError("Некорректный SIP-пароль Mango")
    return value


def validate_port(value: str) -> int:
    try:
        port = int(value or "5060")
    except ValueError as exc:
        raise SipError("Некорректный SIP-порт Mango") from exc
    if port not in {5060, 60000}:
        raise SipError("SIP-порт Mango должен быть 5060 или 60000")
    return port


def render_pjsip_config(settings: dict[str, str]) -> str:
    missing = [key for key in SIP_REQUIRED_KEYS if not settings.get(key)]
    if missing:
        raise SipError("Не заполнены обязательные SIP-настройки")
    server = normalize_server(settings["mango_sip_server"])
    login = validate_login(settings["mango_sip_login"])
    validate_extension(settings.get("mango_extension") or login.rsplit("/", 1)[-1])
    password = validate_password(settings["mango_sip_password"])
    port = validate_port(settings.get("mango_sip_port", "5060"))
    return f"""; Generated by Sushi House Voice Robot. Do not edit manually.
[mango-auth]
type=auth
auth_type=userpass
username={login}
password={password}

[mango-aor]
type=aor
contact=sip:{server}:{port}
qualify_frequency=60

[mango-endpoint]
type=endpoint
transport=transport-udp
context=mango-inbound-locked
disallow=all
allow=alaw
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
dtmf_mode=rfc4733
from_user={login}
from_domain={server}
outbound_auth=mango-auth
aors=mango-aor

[mango-registration]
type=registration
transport=transport-udp
outbound_auth=mango-auth
server_uri=sip:{server}:{port}
client_uri=sip:{login}@{server}
contact_user={login}
retry_interval=30
forbidden_retry_interval=300
expiration=180
line=yes
endpoint=mango-endpoint

[mango-identify]
type=identify
endpoint=mango-endpoint
match={server}
"""


def write_pjsip_config(settings: dict[str, str], path: str | None = None) -> Path:
    target = Path(path or os.getenv("ASTERISK_DYNAMIC_CONFIG", "/runtime/asterisk/pjsip_mango.conf"))
    target.parent.mkdir(parents=True, exist_ok=True)
    content = render_pjsip_config(settings)
    descriptor, temporary_name = tempfile.mkstemp(prefix=".pjsip-", dir=target.parent, text=True)
    try:
        os.write(descriptor, content.encode())
        os.fchmod(descriptor, 0o640)
    finally:
        os.close(descriptor)
    Path(temporary_name).replace(target)
    return target


class AmiClient:
    def __init__(self, host: str, port: int, username: str, secret: str, timeout: float = 3.0):
        self.host = host
        self.port = port
        self.username = username
        self.secret = secret
        self.timeout = timeout

    def _read_frame(self, stream) -> list[str]:
        lines = []
        while True:
            raw_line = stream.readline()
            if not raw_line:
                raise SipError("Asterisk AMI закрыл соединение")
            line = raw_line.decode(errors="replace").rstrip("\r\n")
            if not line:
                return lines
            lines.append(line)

    def _send_action(self, stream, action: str, **values: str) -> list[str]:
        action_id = uuid.uuid4().hex
        fields = {"Action": action, "ActionID": action_id, **values}
        payload = "".join(f"{key}: {value}\r\n" for key, value in fields.items()) + "\r\n"
        stream.write(payload.encode())
        stream.flush()
        for _ in range(100):
            response = self._read_frame(stream)
            if any(line == f"ActionID: {action_id}" for line in response):
                return response
        raise SipError("Asterisk AMI не вернул ответ на команду")

    def action(self, action: str, **values: str) -> list[str]:
        try:
            with socket.create_connection((self.host, self.port), timeout=self.timeout) as connection:
                connection.settimeout(self.timeout)
                stream = connection.makefile("rwb", buffering=0)
                banner = stream.readline().decode(errors="replace")
                if not banner.startswith("Asterisk Call Manager"):
                    raise SipError("Неожиданный ответ Asterisk AMI")
                login = self._send_action(stream, "Login", Username=self.username, Secret=self.secret)
                if not any(line == "Response: Success" for line in login):
                    raise SipError("Asterisk AMI отклонил авторизацию")
                response = self._send_action(stream, action, **values)
                try:
                    self._send_action(stream, "Logoff")
                except SipError:
                    pass
                return response
        except (OSError, TimeoutError) as exc:
            raise SipError(f"Asterisk AMI недоступен: {exc}") from exc

    def command(self, command: str) -> list[str]:
        response = self.action("Command", Command=command)
        return [line[8:] for line in response if line.startswith("Output: ")]

    def originate(self, channel: str, application: str, data: str, caller_id: str, timeout_ms: int = 45000) -> None:
        response = self.action(
            "Originate",
            Channel=channel,
            Application=application,
            Data=data,
            CallerID=caller_id,
            Timeout=str(timeout_ms),
            Async="true",
        )
        if not any(line == "Response: Success" for line in response):
            message = next((line[9:] for line in response if line.startswith("Message: ")), "Originate rejected")
            raise SipError(f"Asterisk не запустил звонок: {message}")


def ami_client() -> AmiClient:
    secret = os.getenv("ASTERISK_AMI_SECRET", "")
    if not secret:
        raise SipError("ASTERISK_AMI_SECRET не настроен")
    return AmiClient(
        os.getenv("ASTERISK_AMI_HOST", "asterisk"),
        int(os.getenv("ASTERISK_AMI_PORT", "5038")),
        os.getenv("ASTERISK_AMI_USER", "voice_robot"),
        secret,
    )


def registration_status() -> SipStatus:
    try:
        output = ami_client().command("pjsip show registrations")
    except SipError as exc:
        return SipStatus("unavailable", "SIP-шлюз недоступен", str(exc))
    registration_line = next((line for line in output if "mango-registration" in line), "")
    if not registration_line:
        return SipStatus("not_configured", "SIP не применён", "Конфигурация Mango не загружена")
    if re.search(r"\bRegistered\b", registration_line):
        return SipStatus("registered", "Зарегистрирован", registration_line.strip(), True)
    if re.search(r"\bRejected\b", registration_line):
        return SipStatus("rejected", "Регистрация отклонена", registration_line.strip())
    return SipStatus("pending", "Ожидается регистрация", registration_line.strip())


def apply_registration(settings: dict[str, str]) -> SipStatus:
    write_pjsip_config(settings)
    ami_client().command("pjsip reload")
    status = registration_status()
    for _ in range(5):
        if status.state not in {"pending", "not_configured"}:
            break
        time.sleep(1)
        status = registration_status()
    return status


def originate_test_call(phone: str, call_id: str, caller_id: str) -> None:
    if not PHONE_PATTERN.fullmatch(phone):
        raise SipError("Тестовый номер должен быть в международном формате")
    dialed_phone = phone.removeprefix("+")
    try:
        uuid.UUID(call_id)
    except ValueError as exc:
        raise SipError("Некорректный идентификатор тестового звонка") from exc
    normalized_caller_id = caller_id.strip()
    if normalized_caller_id and not PHONE_PATTERN.fullmatch(normalized_caller_id):
        raise SipError("Некорректный исходящий Caller ID")
    sip_caller_id = normalized_caller_id.removeprefix("+") if normalized_caller_id else dialed_phone
    ami_client().originate(
        channel=f"PJSIP/{dialed_phone}@mango-endpoint",
        application="AudioSocket",
        data=f"{call_id},app:9092",
        caller_id=sip_caller_id,
    )
